#!/bin/bash
#
# put into /etc/bash_completion.d/
#
_vimus()
{
    local cur prev opts
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    opts='--help --host -h --port -p'

    case "${prev}" in
	--host|-h)
            return 0
            ;;
	--port|-p)
            return 0
            ;;
        *)
            ;;
    esac

    COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
}
complete -F _vimus vimus
